### ISSUE TITLE
Create database design

### ISSUE THREAD

**Issue by R3dIO** [RTX2080-UF/gatorshare-backend#20]
Define database tables and create an ER-diagram

**Comment by R3dIO** [comment]
Reference for ER- diagram
https://vertabelo.com/blog/vertabelo-tips-good-er-diagram-layout/

**Comment by R3dIO** [comment]
@eclairss17 could you please add the ER diagram to this Issue.

**Comment by eclairss17** [comment]
Attaching the Link do the database design, this has the ER diagram for the Backend.

https://uflorida-my.sharepoint.com/:i:/g/personal/ekleenkaur_ufl_edu/EYoTy-Y5TLJPjGKHF7Ufe44B4YOn0Fg-EvORuhMbQYg0KQ?e=BB5yzh

**Comment by eclairss17** [comment]
Attaching the link for the database architecture 

https://uflorida-my.sharepoint.com/:i:/g/personal/ekleenkaur_ufl_edu/EUGflqO7JldAgdJVBWQfZ34BTPZT0rvWB_MN9QSs_17Y2g?e=kgoJBd

**Comment by R3dIO** [comment]
@eclairss17 Great Work!
