### ISSUE TITLE
User should be able to logout

### ISSUE THREAD

**Issue by R3dIO** [RTX2080-UF/gatorshare-backend#4]

**Comment by R3dIO** [comment]
@tatirajurishabh I think you could help me with this issue could you just remove the token from the frontend during logout?

**Comment by tatirajurishabh** [comment]
> @tatirajurishabh I think you could help me with this issue could you just remove the token from the frontend during logout?

Yes the frontend does that currently. 👍

**Comment by R3dIO** [comment]
Sounds good! then I am closing this issue.
